name: "Publish new Version"

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

permissions:
  contents: write
  packages: write


jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.103'
      - name: RunNuke Github Push
        run: ./build.ps1 NuGetPushGitHub --GithubToken ${{ secrets.GITHUB_TOKEN }}
